spring:
  application:
    name: user-service
  datasource:
    validationQuery: SELECT 1
    testWhileIdle: true
  database:
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
  sql:
    init:
      platform: postgres
  output:
    ansi:
      enabled: always
## fetch-registry : Eureka
## service-url defaultZone :
greeting:
  message: hi
